/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.caculadora;

/**
 *
 * @author Kevin Esguerra Cardona
 */
public class FrontEnd2 extends javax.swing.JFrame {
    
    Operador operador = new Operador();
    
    /**
     * Creates new form FrontEnd2
     */
    public FrontEnd2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Display = new javax.swing.JTextField();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonParenthesisOpen = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonParenthesisClose = new javax.swing.JButton();
        ButtonSum = new javax.swing.JButton();
        ButtonDifference = new javax.swing.JButton();
        ButtonCocient = new javax.swing.JButton();
        ButtonProduct = new javax.swing.JButton();
        ButtonErase = new javax.swing.JButton();
        ButtonPoint = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();

        jButton12.setText("jButton12");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Display.setEditable(false);
        Display.setBackground(new java.awt.Color(255, 255, 255));
        Display.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        Button7.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button7.setText("7");
        Button7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button7.setMaximumSize(new java.awt.Dimension(50, 25));
        Button7.setMinimumSize(new java.awt.Dimension(50, 25));
        Button7.setPreferredSize(new java.awt.Dimension(50, 25));
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button8.setText("8");
        Button8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button8.setMaximumSize(new java.awt.Dimension(50, 25));
        Button8.setMinimumSize(new java.awt.Dimension(50, 25));
        Button8.setPreferredSize(new java.awt.Dimension(50, 25));
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button9.setText("9");
        Button9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button9.setMaximumSize(new java.awt.Dimension(50, 25));
        Button9.setMinimumSize(new java.awt.Dimension(50, 25));
        Button9.setPreferredSize(new java.awt.Dimension(50, 25));
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button4.setText("4");
        Button4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button4.setMaximumSize(new java.awt.Dimension(50, 25));
        Button4.setMinimumSize(new java.awt.Dimension(50, 25));
        Button4.setPreferredSize(new java.awt.Dimension(50, 25));
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button5.setText("5");
        Button5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button5.setMaximumSize(new java.awt.Dimension(50, 25));
        Button5.setMinimumSize(new java.awt.Dimension(50, 25));
        Button5.setPreferredSize(new java.awt.Dimension(50, 25));
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button6.setText("6");
        Button6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button6.setMaximumSize(new java.awt.Dimension(50, 25));
        Button6.setMinimumSize(new java.awt.Dimension(50, 25));
        Button6.setPreferredSize(new java.awt.Dimension(50, 25));
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button1.setText("1");
        Button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button1.setMaximumSize(new java.awt.Dimension(50, 25));
        Button1.setMinimumSize(new java.awt.Dimension(50, 25));
        Button1.setPreferredSize(new java.awt.Dimension(50, 25));
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button2.setText("2");
        Button2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button2.setMaximumSize(new java.awt.Dimension(50, 25));
        Button2.setMinimumSize(new java.awt.Dimension(50, 25));
        Button2.setPreferredSize(new java.awt.Dimension(50, 25));
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button3.setText("3");
        Button3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button3.setMaximumSize(new java.awt.Dimension(50, 25));
        Button3.setMinimumSize(new java.awt.Dimension(50, 25));
        Button3.setPreferredSize(new java.awt.Dimension(50, 25));
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        ButtonParenthesisOpen.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonParenthesisOpen.setText("(");
        ButtonParenthesisOpen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonParenthesisOpen.setMaximumSize(new java.awt.Dimension(50, 25));
        ButtonParenthesisOpen.setMinimumSize(new java.awt.Dimension(50, 25));
        ButtonParenthesisOpen.setPreferredSize(new java.awt.Dimension(50, 25));
        ButtonParenthesisOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonParenthesisOpenActionPerformed(evt);
            }
        });

        Button0.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Button0.setText("0");
        Button0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button0.setMaximumSize(new java.awt.Dimension(50, 25));
        Button0.setMinimumSize(new java.awt.Dimension(50, 25));
        Button0.setPreferredSize(new java.awt.Dimension(50, 25));
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        ButtonParenthesisClose.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonParenthesisClose.setText(")");
        ButtonParenthesisClose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonParenthesisClose.setMaximumSize(new java.awt.Dimension(50, 25));
        ButtonParenthesisClose.setMinimumSize(new java.awt.Dimension(50, 25));
        ButtonParenthesisClose.setPreferredSize(new java.awt.Dimension(50, 25));
        ButtonParenthesisClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonParenthesisCloseActionPerformed(evt);
            }
        });

        ButtonSum.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonSum.setText("+");
        ButtonSum.setMaximumSize(new java.awt.Dimension(75, 25));
        ButtonSum.setMinimumSize(new java.awt.Dimension(75, 25));
        ButtonSum.setPreferredSize(new java.awt.Dimension(75, 25));
        ButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSumActionPerformed(evt);
            }
        });

        ButtonDifference.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonDifference.setText("-");
        ButtonDifference.setMaximumSize(new java.awt.Dimension(75, 25));
        ButtonDifference.setMinimumSize(new java.awt.Dimension(75, 25));
        ButtonDifference.setPreferredSize(new java.awt.Dimension(75, 25));
        ButtonDifference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDifferenceActionPerformed(evt);
            }
        });

        ButtonCocient.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonCocient.setText("/");
        ButtonCocient.setMaximumSize(new java.awt.Dimension(75, 25));
        ButtonCocient.setMinimumSize(new java.awt.Dimension(75, 25));
        ButtonCocient.setPreferredSize(new java.awt.Dimension(75, 25));
        ButtonCocient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCocientActionPerformed(evt);
            }
        });

        ButtonProduct.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonProduct.setText("*");
        ButtonProduct.setMaximumSize(new java.awt.Dimension(75, 25));
        ButtonProduct.setMinimumSize(new java.awt.Dimension(75, 25));
        ButtonProduct.setPreferredSize(new java.awt.Dimension(75, 25));
        ButtonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProductActionPerformed(evt);
            }
        });

        ButtonErase.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonErase.setText("E");
        ButtonErase.setMaximumSize(new java.awt.Dimension(75, 25));
        ButtonErase.setMinimumSize(new java.awt.Dimension(75, 25));
        ButtonErase.setPreferredSize(new java.awt.Dimension(75, 25));
        ButtonErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEraseActionPerformed(evt);
            }
        });

        ButtonPoint.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonPoint.setText(".");
        ButtonPoint.setMaximumSize(new java.awt.Dimension(75, 25));
        ButtonPoint.setMinimumSize(new java.awt.Dimension(75, 25));
        ButtonPoint.setPreferredSize(new java.awt.Dimension(75, 25));
        ButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPointActionPerformed(evt);
            }
        });

        ButtonEqual.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        ButtonEqual.setText("=");
        ButtonEqual.setMaximumSize(new java.awt.Dimension(75, 25));
        ButtonEqual.setMinimumSize(new java.awt.Dimension(75, 25));
        ButtonEqual.setPreferredSize(new java.awt.Dimension(75, 25));
        ButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Display)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ButtonParenthesisOpen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonParenthesisClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonErase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonDifference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonCocient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDifference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCocient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonParenthesisOpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonParenthesisClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonErase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonParenthesisOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonParenthesisOpenActionPerformed
        AddValue("(");
    }//GEN-LAST:event_ButtonParenthesisOpenActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        AddValue("7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        AddValue("5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void ButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEqualActionPerformed
        Display.setText(operador.operar(Display.getText()));
    }//GEN-LAST:event_ButtonEqualActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        AddValue("0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        AddValue("8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        AddValue("9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        AddValue("4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        AddValue("6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        AddValue("1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        AddValue("2");
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        AddValue("3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void ButtonParenthesisCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonParenthesisCloseActionPerformed
        AddValue(")");
    }//GEN-LAST:event_ButtonParenthesisCloseActionPerformed

    private void ButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSumActionPerformed
        AddValue("+");
    }//GEN-LAST:event_ButtonSumActionPerformed

    private void ButtonDifferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDifferenceActionPerformed
        AddValue("-");
    }//GEN-LAST:event_ButtonDifferenceActionPerformed

    private void ButtonCocientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCocientActionPerformed
        AddValue("/");
    }//GEN-LAST:event_ButtonCocientActionPerformed

    private void ButtonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProductActionPerformed
        AddValue("*");
    }//GEN-LAST:event_ButtonProductActionPerformed

    private void ButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPointActionPerformed
        AddValue(".");
    }//GEN-LAST:event_ButtonPointActionPerformed

    private void ButtonEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEraseActionPerformed
        CleanDisplay();
    }//GEN-LAST:event_ButtonEraseActionPerformed
    
    private void AddValue(String value) {
        Display.setText(Display.getText()+value);
    }
    
    private void CleanDisplay() {
        Display.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Button0;
    public javax.swing.JButton Button1;
    public javax.swing.JButton Button2;
    public javax.swing.JButton Button3;
    public javax.swing.JButton Button4;
    public javax.swing.JButton Button5;
    public javax.swing.JButton Button6;
    public javax.swing.JButton Button7;
    public javax.swing.JButton Button8;
    public javax.swing.JButton Button9;
    public javax.swing.JButton ButtonCocient;
    public javax.swing.JButton ButtonDifference;
    public javax.swing.JButton ButtonEqual;
    public javax.swing.JButton ButtonErase;
    public javax.swing.JButton ButtonParenthesisClose;
    public javax.swing.JButton ButtonParenthesisOpen;
    public javax.swing.JButton ButtonPoint;
    public javax.swing.JButton ButtonProduct;
    public javax.swing.JButton ButtonSum;
    public javax.swing.JTextField Display;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
