/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tictactoe;

import java.util.Map;

/**
 *
 * @author xdpor
 */
public class EndGameView extends javax.swing.JFrame {
    private final Map<Integer, Player> players;

    /**
     * Creates new form EndGameView
     * @param players
     */
    public EndGameView(Map<Integer, Player> players) {
        initComponents();
        this.players = players;
        
        LabelPlayer1Name.setText(players.get(1).getName());
        LabelPlayer1Points.setText(players.get(1).getPunctuation());
        LabelPlayer2Name.setText(players.get(2).getName());
        LabelPlayer2Points.setText(players.get(2).getPunctuation());
        
        if (players.get(1).getPunctuation().equals(players.get(2).getPunctuation())) {
            LabelWinner.setText("Nobody");
        } else if (Integer.valueOf(players.get(1).getPunctuation()) > Integer.valueOf(players.get(2).getPunctuation())) {
            LabelWinner.setText(players.get(1).getName());
        } else {
            LabelWinner.setText(players.get(2).getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelPlayer1Name = new javax.swing.JLabel();
        LabelPlayer2Name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelPlayer1Points = new javax.swing.JLabel();
        LabelPlayer2Points = new javax.swing.JLabel();
        LabelWinner = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        ButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(310, 180));
        setMinimumSize(new java.awt.Dimension(310, 180));

        LabelTitle.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("TicTacToe");

        jLabel1.setText("Players");

        LabelPlayer1Name.setText("<<Player1.name>>");

        LabelPlayer2Name.setText("<<Player2.name>>");

        jLabel4.setText("Points");

        LabelPlayer1Points.setText("<<Player1.points>>");

        LabelPlayer2Points.setText("<<Player2.points>>");

        LabelWinner.setText("<<Winner.name>>");

        jLabel8.setText("won");

        ButtonExit.setText("Exit");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelWinner)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(LabelPlayer1Name)
                            .addComponent(LabelPlayer2Name))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPlayer2Points)
                            .addComponent(LabelPlayer1Points)
                            .addComponent(jLabel4)))
                    .addComponent(jSeparator1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPlayer1Name)
                    .addComponent(LabelPlayer1Points))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPlayer2Name)
                    .addComponent(LabelPlayer2Points))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelWinner)
                    .addComponent(jLabel8)
                    .addComponent(ButtonExit))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExit;
    private javax.swing.JLabel LabelPlayer1Name;
    private javax.swing.JLabel LabelPlayer1Points;
    private javax.swing.JLabel LabelPlayer2Name;
    private javax.swing.JLabel LabelPlayer2Points;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JLabel LabelWinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
