/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.scientificcalculator;

import java.util.List;
import java.util.ArrayList;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

/**
 *
 * @author Kevin Esguerra Cardona
 */
public class MainView extends javax.swing.JFrame {    
    List<javax.swing.JButton> TrigoFunctionButtons = new ArrayList<>();
    Pattern hyperbolicFunctionPattern;
    Pattern inverseFunctionPattern;
    Controller operator = new Controller();

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        TrigoFunctionButtons.add(ButtonSen);
        TrigoFunctionButtons.add(ButtonCos);
        TrigoFunctionButtons.add(ButtonTan);
        TrigoFunctionButtons.add(ButtonSec);
        TrigoFunctionButtons.add(ButtonCsc);
        TrigoFunctionButtons.add(ButtonCot);
        hyperbolicFunctionPattern = Pattern.compile("(sen|cos|tan|sec|csc|cot|arcsen|arccos|arctan|arcsec|arccsc|arccot)(h?\\(x\\))");
        inverseFunctionPattern = Pattern.compile("(arc)?(sen|cos|tan|sec|csc|cot)(h?\\(x\\))");
        DisplayExpression.setText("");
        DisplayResult.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        DisplayResult = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ButtonTransformToInverseFunctions = new javax.swing.JButton();
        ButtonSen = new javax.swing.JButton();
        ButtonCos = new javax.swing.JButton();
        ButtonTan = new javax.swing.JButton();
        DisplayExpression = new javax.swing.JTextField();
        ButtonTrasnformToHyperbolicFunctions = new javax.swing.JButton();
        ButtonSec = new javax.swing.JButton();
        ButtonCsc = new javax.swing.JButton();
        ButtonCot = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        ButtonNumberPi = new javax.swing.JButton();
        ButtonNumberE = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        ButtonOneOverX = new javax.swing.JButton();
        ButtonAbs = new javax.swing.JButton();
        ButtonExponentialNotation = new javax.swing.JButton();
        ButtonModule = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        ButtonToOpenParenthesis = new javax.swing.JButton();
        ButtonToCloseParenthesis = new javax.swing.JButton();
        ButtonFactorial = new javax.swing.JButton();
        ButtonDivision = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        ButtonNumber7 = new javax.swing.JButton();
        ButtonNumber8 = new javax.swing.JButton();
        ButtonNumber9 = new javax.swing.JButton();
        ButtonProduct = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        ButtonNumber4 = new javax.swing.JButton();
        ButtonNumber5 = new javax.swing.JButton();
        ButtonNumber6 = new javax.swing.JButton();
        ButtonDifference = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        ButtonNumber1 = new javax.swing.JButton();
        ButtonNumber2 = new javax.swing.JButton();
        ButtonNumber3 = new javax.swing.JButton();
        ButtonSum = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        ButtonToChangeSign = new javax.swing.JButton();
        ButtonNumber0 = new javax.swing.JButton();
        ButtonComma = new javax.swing.JButton();
        ButtonEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(250, 250));
        setMaximumSize(new java.awt.Dimension(370, 520));
        setMinimumSize(new java.awt.Dimension(370, 520));
        setPreferredSize(new java.awt.Dimension(370, 520));
        setResizable(false);
        setSize(new java.awt.Dimension(370, 520));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);
        jTextField1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        DisplayResult.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        DisplayResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DisplayResult.setText("4");
        DisplayResult.setAutoscrolls(false);
        DisplayResult.setBorder(null);
        DisplayResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DisplayResult.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DisplayResult.setEnabled(false);
        DisplayResult.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ButtonTransformToInverseFunctions.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonTransformToInverseFunctions.setText("arc");
        ButtonTransformToInverseFunctions.setBorder(null);
        ButtonTransformToInverseFunctions.setBorderPainted(false);
        ButtonTransformToInverseFunctions.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonTransformToInverseFunctions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonTransformToInverseFunctions.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonTransformToInverseFunctions.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonTransformToInverseFunctions.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonTransformToInverseFunctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransformToInverseFunctionsActionPerformed(evt);
            }
        });

        ButtonSen.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonSen.setText("sen(x)");
        ButtonSen.setBorder(null);
        ButtonSen.setBorderPainted(false);
        ButtonSen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonSen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonSen.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonSen.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonSen.setPreferredSize(new java.awt.Dimension(70, 30));

        ButtonCos.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonCos.setText("cos(x)");
        ButtonCos.setBorder(null);
        ButtonCos.setBorderPainted(false);
        ButtonCos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonCos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonCos.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonCos.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonCos.setPreferredSize(new java.awt.Dimension(70, 30));

        ButtonTan.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonTan.setText("tan(x)");
        ButtonTan.setBorder(null);
        ButtonTan.setBorderPainted(false);
        ButtonTan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonTan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonTan.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonTan.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonTan.setPreferredSize(new java.awt.Dimension(70, 30));

        DisplayExpression.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        DisplayExpression.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DisplayExpression.setText("2+3");
        DisplayExpression.setAutoscrolls(false);
        DisplayExpression.setBorder(null);
        DisplayExpression.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DisplayExpression.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        DisplayExpression.setEnabled(false);
        DisplayExpression.setMargin(new java.awt.Insets(0, 0, 0, 0));
        DisplayExpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayExpressionActionPerformed(evt);
            }
        });

        ButtonTrasnformToHyperbolicFunctions.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonTrasnformToHyperbolicFunctions.setText("hyp");
        ButtonTrasnformToHyperbolicFunctions.setBorder(null);
        ButtonTrasnformToHyperbolicFunctions.setBorderPainted(false);
        ButtonTrasnformToHyperbolicFunctions.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonTrasnformToHyperbolicFunctions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonTrasnformToHyperbolicFunctions.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonTrasnformToHyperbolicFunctions.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonTrasnformToHyperbolicFunctions.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonTrasnformToHyperbolicFunctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTrasnformToHyperbolicFunctionsActionPerformed(evt);
            }
        });

        ButtonSec.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonSec.setText("sec(x)");
        ButtonSec.setBorder(null);
        ButtonSec.setBorderPainted(false);
        ButtonSec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonSec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonSec.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonSec.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonSec.setPreferredSize(new java.awt.Dimension(70, 30));

        ButtonCsc.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonCsc.setText("csc(x)");
        ButtonCsc.setBorder(null);
        ButtonCsc.setBorderPainted(false);
        ButtonCsc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonCsc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonCsc.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonCsc.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonCsc.setPreferredSize(new java.awt.Dimension(70, 30));

        ButtonCot.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonCot.setText("cot(x)");
        ButtonCot.setBorder(null);
        ButtonCot.setBorderPainted(false);
        ButtonCot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonCot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonCot.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonCot.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonCot.setPreferredSize(new java.awt.Dimension(70, 30));

        jButton11.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jButton11.setText("2nd");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton11.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton11.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonNumberPi.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumberPi.setText("Pi");
        ButtonNumberPi.setBorder(null);
        ButtonNumberPi.setBorderPainted(false);
        ButtonNumberPi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumberPi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumberPi.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumberPi.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumberPi.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonNumberE.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumberE.setText("e");
        ButtonNumberE.setBorder(null);
        ButtonNumberE.setBorderPainted(false);
        ButtonNumberE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumberE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumberE.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumberE.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumberE.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonClear.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonClear.setText("C");
        ButtonClear.setBorder(null);
        ButtonClear.setBorderPainted(false);
        ButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonClear.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonClear.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonClear.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        ButtonDelete.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonDelete.setText("Delete");
        ButtonDelete.setBorder(null);
        ButtonDelete.setBorderPainted(false);
        ButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonDelete.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonDelete.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonDelete.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jButton16.setText("x^2");
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton16.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton16.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonOneOverX.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonOneOverX.setText("1/x");
        ButtonOneOverX.setBorder(null);
        ButtonOneOverX.setBorderPainted(false);
        ButtonOneOverX.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonOneOverX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonOneOverX.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonOneOverX.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonOneOverX.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonAbs.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonAbs.setText("|x|");
        ButtonAbs.setBorder(null);
        ButtonAbs.setBorderPainted(false);
        ButtonAbs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonAbs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonAbs.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonAbs.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonAbs.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonExponentialNotation.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonExponentialNotation.setText("exp");
        ButtonExponentialNotation.setBorder(null);
        ButtonExponentialNotation.setBorderPainted(false);
        ButtonExponentialNotation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonExponentialNotation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonExponentialNotation.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonExponentialNotation.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonExponentialNotation.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonModule.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonModule.setText("mod");
        ButtonModule.setBorder(null);
        ButtonModule.setBorderPainted(false);
        ButtonModule.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonModule.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonModule.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonModule.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonModule.setPreferredSize(new java.awt.Dimension(55, 30));

        jButton21.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jButton21.setText("sqrt(x)");
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton21.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton21.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonToOpenParenthesis.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonToOpenParenthesis.setText("(");
        ButtonToOpenParenthesis.setBorder(null);
        ButtonToOpenParenthesis.setBorderPainted(false);
        ButtonToOpenParenthesis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonToOpenParenthesis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonToOpenParenthesis.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonToOpenParenthesis.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonToOpenParenthesis.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonToOpenParenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToOpenParenthesisActionPerformed(evt);
            }
        });

        ButtonToCloseParenthesis.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonToCloseParenthesis.setText(")");
        ButtonToCloseParenthesis.setBorder(null);
        ButtonToCloseParenthesis.setBorderPainted(false);
        ButtonToCloseParenthesis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonToCloseParenthesis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonToCloseParenthesis.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonToCloseParenthesis.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonToCloseParenthesis.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonToCloseParenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToCloseParenthesisActionPerformed(evt);
            }
        });

        ButtonFactorial.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonFactorial.setText("n!");
        ButtonFactorial.setBorder(null);
        ButtonFactorial.setBorderPainted(false);
        ButtonFactorial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonFactorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonFactorial.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonFactorial.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonFactorial.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonDivision.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonDivision.setText("/");
        ButtonDivision.setBorder(null);
        ButtonDivision.setBorderPainted(false);
        ButtonDivision.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonDivision.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonDivision.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonDivision.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonDivision.setPreferredSize(new java.awt.Dimension(55, 30));

        jButton26.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jButton26.setText("x^y");
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton26.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton26.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonNumber7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber7.setText("7");
        ButtonNumber7.setBorder(null);
        ButtonNumber7.setBorderPainted(false);
        ButtonNumber7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber7.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber7.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber7.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber7ActionPerformed(evt);
            }
        });

        ButtonNumber8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber8.setText("8");
        ButtonNumber8.setBorder(null);
        ButtonNumber8.setBorderPainted(false);
        ButtonNumber8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber8.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber8.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber8.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber8ActionPerformed(evt);
            }
        });

        ButtonNumber9.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber9.setText("9");
        ButtonNumber9.setBorder(null);
        ButtonNumber9.setBorderPainted(false);
        ButtonNumber9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber9.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber9.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber9.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber9ActionPerformed(evt);
            }
        });

        ButtonProduct.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonProduct.setText("*");
        ButtonProduct.setBorder(null);
        ButtonProduct.setBorderPainted(false);
        ButtonProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonProduct.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonProduct.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonProduct.setPreferredSize(new java.awt.Dimension(55, 30));

        jButton31.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jButton31.setText("10^x");
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton31.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton31.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonNumber4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber4.setText("4");
        ButtonNumber4.setBorder(null);
        ButtonNumber4.setBorderPainted(false);
        ButtonNumber4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber4.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber4.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber4.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber4ActionPerformed(evt);
            }
        });

        ButtonNumber5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber5.setText("5");
        ButtonNumber5.setBorder(null);
        ButtonNumber5.setBorderPainted(false);
        ButtonNumber5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber5.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber5.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber5.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber5ActionPerformed(evt);
            }
        });

        ButtonNumber6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber6.setText("6");
        ButtonNumber6.setBorder(null);
        ButtonNumber6.setBorderPainted(false);
        ButtonNumber6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber6.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber6.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber6.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber6ActionPerformed(evt);
            }
        });

        ButtonDifference.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonDifference.setText("-");
        ButtonDifference.setBorder(null);
        ButtonDifference.setBorderPainted(false);
        ButtonDifference.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonDifference.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonDifference.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonDifference.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonDifference.setPreferredSize(new java.awt.Dimension(55, 30));

        jButton36.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jButton36.setText("log");
        jButton36.setBorder(null);
        jButton36.setBorderPainted(false);
        jButton36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton36.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton36.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton36.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonNumber1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber1.setText("1");
        ButtonNumber1.setBorder(null);
        ButtonNumber1.setBorderPainted(false);
        ButtonNumber1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber1.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber1.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber1.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber1ActionPerformed(evt);
            }
        });

        ButtonNumber2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber2.setText("2");
        ButtonNumber2.setBorder(null);
        ButtonNumber2.setBorderPainted(false);
        ButtonNumber2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber2.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber2.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber2.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber2ActionPerformed(evt);
            }
        });

        ButtonNumber3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber3.setText("3");
        ButtonNumber3.setBorder(null);
        ButtonNumber3.setBorderPainted(false);
        ButtonNumber3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber3.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber3.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber3.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber3ActionPerformed(evt);
            }
        });

        ButtonSum.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonSum.setText("+");
        ButtonSum.setBorder(null);
        ButtonSum.setBorderPainted(false);
        ButtonSum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonSum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonSum.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonSum.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonSum.setPreferredSize(new java.awt.Dimension(55, 30));

        jButton41.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jButton41.setText("ln");
        jButton41.setBorder(null);
        jButton41.setBorderPainted(false);
        jButton41.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton41.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton41.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton41.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonToChangeSign.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonToChangeSign.setText("+/-");
        ButtonToChangeSign.setBorder(null);
        ButtonToChangeSign.setBorderPainted(false);
        ButtonToChangeSign.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonToChangeSign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonToChangeSign.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonToChangeSign.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonToChangeSign.setPreferredSize(new java.awt.Dimension(55, 30));

        ButtonNumber0.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonNumber0.setText("0");
        ButtonNumber0.setBorder(null);
        ButtonNumber0.setBorderPainted(false);
        ButtonNumber0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonNumber0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNumber0.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonNumber0.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonNumber0.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNumber0ActionPerformed(evt);
            }
        });

        ButtonComma.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonComma.setText(",");
        ButtonComma.setBorder(null);
        ButtonComma.setBorderPainted(false);
        ButtonComma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonComma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonComma.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonComma.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonComma.setPreferredSize(new java.awt.Dimension(55, 30));
        ButtonComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCommaActionPerformed(evt);
            }
        });

        ButtonEqual.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        ButtonEqual.setText("=");
        ButtonEqual.setBorder(null);
        ButtonEqual.setBorderPainted(false);
        ButtonEqual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ButtonEqual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEqual.setMaximumSize(new java.awt.Dimension(50, 20));
        ButtonEqual.setMinimumSize(new java.awt.Dimension(50, 20));
        ButtonEqual.setPreferredSize(new java.awt.Dimension(55, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DisplayResult, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DisplayExpression, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumberPi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumberE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonOneOverX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonAbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonExponentialNotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonToOpenParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonToCloseParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonDifference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonToChangeSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonComma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButtonTransformToInverseFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonSen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButtonTrasnformToHyperbolicFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButtonCsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonCot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTransformToInverseFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTrasnformToHyperbolicFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumberPi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumberE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonOneOverX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonExponentialNotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonToOpenParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonToCloseParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDifference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonToChangeSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonComma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Main View");
        getAccessibleContext().setAccessibleDescription("Calculator's Main View");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void DisplayExpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayExpressionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayExpressionActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        DisplayExpression.setText("");
        DisplayResult.setText("");
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonTransformToInverseFunctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransformToInverseFunctionsActionPerformed
        for (javax.swing.JButton button : TrigoFunctionButtons) {
            Matcher matcher = inverseFunctionPattern.matcher(button.getText());
            if (matcher.find()) {
                button.setText(matcher.group(1) != null ? matcher.group(2) + matcher.group(3) : "arc" + matcher.group(2) + matcher.group(3));
            }
        }
    }//GEN-LAST:event_ButtonTransformToInverseFunctionsActionPerformed

    private void ButtonTrasnformToHyperbolicFunctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTrasnformToHyperbolicFunctionsActionPerformed
        for (javax.swing.JButton button : TrigoFunctionButtons) {
            Matcher matcher = hyperbolicFunctionPattern.matcher(button.getText());
            if (matcher.find()) {
                button.setText(matcher.group(2).equals("h(x)") ? matcher.group(1) + "(x)" : matcher.group(1) + "h(x)");
            }
        }
    }//GEN-LAST:event_ButtonTrasnformToHyperbolicFunctionsActionPerformed

    private void ButtonNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber0ActionPerformed
        AddValueToExpression("0");
    }//GEN-LAST:event_ButtonNumber0ActionPerformed

    private void ButtonCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCommaActionPerformed
        AddValueToExpression(",");
    }//GEN-LAST:event_ButtonCommaActionPerformed

    private void ButtonNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber1ActionPerformed
        AddValueToExpression("1");
    }//GEN-LAST:event_ButtonNumber1ActionPerformed

    private void ButtonNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber2ActionPerformed
        AddValueToExpression("2");
    }//GEN-LAST:event_ButtonNumber2ActionPerformed

    private void ButtonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber3ActionPerformed
        AddValueToExpression("3");
    }//GEN-LAST:event_ButtonNumber3ActionPerformed

    private void ButtonNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber4ActionPerformed
        AddValueToExpression("4");
    }//GEN-LAST:event_ButtonNumber4ActionPerformed

    private void ButtonNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber5ActionPerformed
        AddValueToExpression("5");
    }//GEN-LAST:event_ButtonNumber5ActionPerformed

    private void ButtonNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber6ActionPerformed
        AddValueToExpression("6");
    }//GEN-LAST:event_ButtonNumber6ActionPerformed

    private void ButtonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber7ActionPerformed
        AddValueToExpression("7");
    }//GEN-LAST:event_ButtonNumber7ActionPerformed

    private void ButtonNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber8ActionPerformed
        AddValueToExpression("8");
    }//GEN-LAST:event_ButtonNumber8ActionPerformed

    private void ButtonNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNumber9ActionPerformed
        AddValueToExpression("9");
    }//GEN-LAST:event_ButtonNumber9ActionPerformed

    private void ButtonToOpenParenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToOpenParenthesisActionPerformed
        AddValueToExpression("(");
    }//GEN-LAST:event_ButtonToOpenParenthesisActionPerformed

    private void ButtonToCloseParenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToCloseParenthesisActionPerformed
        AddValueToExpression(")");
    }//GEN-LAST:event_ButtonToCloseParenthesisActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        String text = DisplayExpression.getText();
        DisplayExpression.setText(text.equals("") ? "" : text.substring(0, text.length() - 1)); 
    }//GEN-LAST:event_ButtonDeleteActionPerformed
    
    private void AddValueToExpression(String value) {
        DisplayExpression.setText(DisplayExpression.getText() + value);
    }
    
    private void UpdateResult() {
        String result = operator.ToSolve(DisplayExpression.getText());
        DisplayResult.setText(result.equals("Syntax Error") ? "" : result);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonAbs;
    public javax.swing.JButton ButtonClear;
    public javax.swing.JButton ButtonComma;
    public javax.swing.JButton ButtonCos;
    public javax.swing.JButton ButtonCot;
    public javax.swing.JButton ButtonCsc;
    public javax.swing.JButton ButtonDelete;
    public javax.swing.JButton ButtonDifference;
    public javax.swing.JButton ButtonDivision;
    public javax.swing.JButton ButtonEqual;
    public javax.swing.JButton ButtonExponentialNotation;
    public javax.swing.JButton ButtonFactorial;
    public javax.swing.JButton ButtonModule;
    public javax.swing.JButton ButtonNumber0;
    public javax.swing.JButton ButtonNumber1;
    public javax.swing.JButton ButtonNumber2;
    public javax.swing.JButton ButtonNumber3;
    public javax.swing.JButton ButtonNumber4;
    public javax.swing.JButton ButtonNumber5;
    public javax.swing.JButton ButtonNumber6;
    public javax.swing.JButton ButtonNumber7;
    public javax.swing.JButton ButtonNumber8;
    public javax.swing.JButton ButtonNumber9;
    public javax.swing.JButton ButtonNumberE;
    public javax.swing.JButton ButtonNumberPi;
    public javax.swing.JButton ButtonOneOverX;
    public javax.swing.JButton ButtonProduct;
    public javax.swing.JButton ButtonSec;
    public javax.swing.JButton ButtonSen;
    public javax.swing.JButton ButtonSum;
    public javax.swing.JButton ButtonTan;
    public javax.swing.JButton ButtonToChangeSign;
    public javax.swing.JButton ButtonToCloseParenthesis;
    public javax.swing.JButton ButtonToOpenParenthesis;
    public javax.swing.JButton ButtonTransformToInverseFunctions;
    public javax.swing.JButton ButtonTrasnformToHyperbolicFunctions;
    public javax.swing.JTextField DisplayExpression;
    public javax.swing.JTextField DisplayResult;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton16;
    public javax.swing.JButton jButton21;
    public javax.swing.JButton jButton26;
    public javax.swing.JButton jButton31;
    public javax.swing.JButton jButton36;
    public javax.swing.JButton jButton41;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
